### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by EvanED** [libor-vilimek/marine-hell#1]
Would you be willing to explicitly license your bot under something that lets other people modify it and such?

(Specifically, I'd like to port it to C++ and put it out there as sort of an example *C++* bot that is both pretty simple but is still capable of winning. From what I can tell, there's the example bot that comes with the BWAPI distribution that doesn't really do anything at all, and then complex bots; like the SSCAIT page recommends going to Steamhammer. I think there's a gap in the middle that MH could fill, for people who want to write in C++. I have no intention of uploading it to the ladder.)

**Comment by dgant** [comment]
Someone expressed interest the other day in using Marine Hell as a performance benchmark across Java frameworks. Marine Hell has developed quite a reputation as a canonical miniature bot :smile:

**Comment by libor-vilimek** [comment]
@EvanED @dgant - hey guys, thanks for pinging, I put MIT licence, this repo was intended to be re/used by whoever wants
